{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: todo-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    {{- include "todo-app.postgres.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    {{- include "todo-app.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
