apiVersion: v2
name: todo-app
description: A Helm chart for the Todo Application (Phase IV)
type: application
version: 0.1.0
appVersion: "0.3.0"

keywords:
  - todo
  - fastapi
  - nextjs
  - kubernetes

maintainers:
  - name: Todo Team
    email: team@example.com

sources:
  - https://github.com/yasmin191/hackathon-todo-evolution
